# Generated by Django 2.0.3 on 2018-03-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_card_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.BankCard')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Account')),
            ],
        ),
    ]
