# Generated by Django 2.0.3 on 2018-03-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('phone_num', models.CharField(max_length=11)),
                ('bank_card_num', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('paycode', models.CharField(max_length=6)),
                ('balance', models.BigIntegerField(default=0)),
                ('currency', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('id_card_num', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('birthday', models.DateField()),
                ('age', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='bankcard',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Identity'),
        ),
    ]
